collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.04121864
color:
  saturation: 0.09240517
  lightness: 0.9375624
  brandStrength: 0.9964158
  brandColors:
    - '#88A2D0'
    - '#657788'
    - '#384C5C'
    - '#0E0C0E'
    - '#A49988'
  rhythmicContrast: 0.6482142
layout_spectrum: 1
name: Japan Tour - 14-22 Nov 2015
